<a href="https://colab.research.google.com/github/paigeclark0615/MAT494/blob/main/Hmwk3_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
# load the dataset
mnist = tf.keras.datasets.mnist

# convert the samples from integers to floating-point numbers
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.1956442 ,  0.09071777,  0.15441975, -0.50600326,  0.41770586,
        -1.2203357 ,  0.37940565, -0.3421197 , -0.27639377, -0.27285925]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.08945734, 0.1191191 , 0.12695412, 0.06558866, 0.16519257,
        0.03210688, 0.1589853 , 0.0772685 , 0.08251765, 0.08280984]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

3.438685

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2971 - accuracy: 0.9139
Epoch 2/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1433 - accuracy: 0.9573
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1079 - accuracy: 0.9675
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0870 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0745 - accuracy: 0.9768


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0722 - accuracy: 0.9764 - 867ms/epoch - 3ms/step


[0.07215619087219238, 0.9764000177383423]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.91430360e-07, 3.86907111e-08, 2.83188674e-05, 1.87433601e-04,
        9.55399713e-13, 1.38827119e-07, 3.76193209e-15, 9.99783218e-01,
        7.70267121e-08, 5.99960458e-07],
       [2.74594854e-08, 6.54787727e-05, 9.99928236e-01, 3.83465567e-06,
        2.49009264e-15, 2.11046790e-06, 2.65496112e-07, 1.44818565e-13,
        1.11554549e-07, 6.59385537e-14],
       [1.63533983e-07, 9.99626637e-01, 5.47573072e-05, 4.58849081e-06,
        1.11069085e-05, 2.93027801e-06, 4.56240414e-05, 1.81579700e-04,
        7.24591591e-05, 1.23964668e-07],
       [9.99980807e-01, 2.18856391e-10, 5.40756173e-06, 1.49601522e-06,
        3.10351567e-08, 3.30520862e-07, 8.59410102e-06, 2.01347916e-06,
        5.06589174e-07, 9.29060775e-07],
       [1.75784498e-06, 2.62114025e-10, 2.90149319e-06, 1.60043996e-08,
        9.99000132e-01, 7.60591092e-08, 4.31774623e-07, 2.44718849e-05,
        1.44934560e-07, 9.70108900e-04]], dtype=float32)>